# Generated by Django 4.2.2 on 2023-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=200, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Пароль'),
        ),
    ]
