# Generated by Django 4.2.2 on 2023-06-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_door_price_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=200, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('date', models.DateField(max_length=200, verbose_name='Дата доставки')),
            ],
        ),
    ]
